
export const SELECTION_EMPTY = "SELECTION_EMPTY";
export const SELECTION_VEHICLE = "SELECTION_VEHICLE";
export const SELECTION_ROUTE = "SELECTION_ROUTE";
export const SELECTION_STOP = "SELECTION_STOP";
export const SELECTION_STOP_AND_ROUTE = "SELECTION_STOP_AND_ROUTE";
